### ISSUE TITLE
collectd.env

### ISSUE THREAD

**Issue by janishorsts** [responsivecraft/dockerised-mysql-monitoring#3]
@kaaposc , we need to find a cleaner solution for env variables. This file is part of repo, and users shouldn't edit files that are part of the code base.

**Comment by kaaposc** [comment]
We can get rid of `collectd.env` entirely by introducing bootstrap script for starting `docker-compose`. It will also make collectd image more immutable by removing `entrypoint.sh`.
1. Bootstrap script reads `collectd.yml` for variables to create `collectd.conf` file that is passed to collectd image.
2. Script accepts command line parameters (-h, -u, -p etc.) that override those in `collectd.yml`.
3. Script accepts environment variables that override all above.

**Comment by janishorsts** [comment]
1. & 3. are not needed, all configuration is defined only in yaml file.

What structure do you intend to use in yaml? Do you plan to use bash to generate collectd.conf file from collectd.yml?

**Comment by janishorsts** [comment]
And yaml file is not part of git repo. We either describe it in README or create example file - collectd.conf.example.

**Comment by kaaposc** [comment]
All config in one place gives less flexibility.

```
mysql:
  - <server_alias>:
    host: <mysql_host>
    user: <mysql_user>
    password: <mysql_password> # overriding: this < cmd line params < env vars
    port: <mysql_port> # optional, defaults to 3306
  - <server_2_alias>:
    ...
network:
  server: logstash
  port: 25826
```

Thus multiple mysql servers can be configured to monitor. It all gets translated to:

```
<Plugin "mysql">
  <Database "server_alias">
    Host "mysql_host"
    User "mysql_user"
    Password "mysql_password"
    Port "mysql_port"
    InnodbStats true
  </Database>
  <Database "server_2_alias">
    ...
  </Database>
</Plugin>
<Plugin "network">
  Server "logstash" "25826"
</Plugin>
```
